### ISSUE TITLE
Return multiple values not only record

### ISSUE THREAD

**Issue by bulemoon** [SNakano/fluent-plugin-script#5]
I want to rewrite tag and filter it later, does the plugin support this?

**Comment by SNakano** [comment]
No, the return value of the filter method is only the record variable or nil.
please see: [Fluentd v0.14 Plugin API Details (p20)](https://image.slidesharecdn.com/fluentdmeetup2016summerpluginapis-160602030358/95/fluentd-v014-plugin-api-details-20-638.jpg?cb=1464836694)
